apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-uploader.fullname" . }}
  labels:
    {{- include "music-uploader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: 32000
      protocol: TCP
    - name: websocket
      port: {{ .Values.websocket.port }}
      targetPort: 32222
      protocol: TCP
  selector:
    {{- include "music-uploader.selectorLabels" . | nindent 4 }}
