apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-uploader.fullname" . }}
  labels:
    {{- include "music-uploader.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      nodePort: 32200
      protocol: TCP
    - name: websocket
      port: 8222
      targetPort: 8222
      nodePort: 32222
      protocol: TCP
  selector:
    {{- include "music-uploader.selectorLabels" . | nindent 4 }}
